gateway/src/main/java/com/sparta/gateway/LocalAuthenticationFilter.java, gateway/src/main/java/com/sparta/gateway/jwt/JwtUtil.java, gateway/src/main/resources/application.yml
- feature/gateway -> develop
- application.yml route 정보 수정
- jwtUtil의 secretKey에서 올바른 정보를 참조하도록 수정
- filter에서 올바른 헤더를 설정하도록 수정
=> refactor: Gateway 설정 및 헤더 설정 로직 수정

gateway/src/main/java/com/sparta/gateway/filter/LocalAuthenticationFilter.java
- feature/gateway -> develop
- 회원가입 엔드포인트 변경에 따라 filter를 적용하지 않을 경로 수정
- 로그인 엔드포인트도 /login이 누락되어 추가
=> refactor: 회원가입 엔드포인트 변경에 따라 filter를 적용하지 않을 경로 수정

user/src/main/java/com/sparta/user/domain/controller/AuthController.java
- feature/{도메인}-api -> main
- 로그인 엔드포인트를 기존 /api/v1/auth에서 /api/v1/auth/login으로 변경
=> refactor: 로그인 엔드포인트 변경

user/build.gradle, user/src/main/java/com/sparta/user/config/QueryDslConfig.java, user/src/main/java/com/sparta/user/domain/controller/UserController.java, user/src/main/java/com/sparta/user/domain/dto/response/UserResponseDto.java, user/src/main/java/com/sparta/user/domain/service/UserService.java, user/src/main/java/com/sparta/user/model/repository/UserRepository.java, user/src/main/java/com/sparta/user/model/repository/UserRepositoryCustom.java, user/src/main/java/com/sparta/user/model/repository/UserRepositoryCustomImpl.java
- feature/user-api -> develop
- QueryDsl을 통해 username, nickname을 기반으로 검색하는 기능 구현
=> feat: 회원 검색 기능 구현

ai/build.gradle, ai/src/main/java/com/sparta/ai/config/QueryDslConfig.java, ai/src/main/java/com/sparta/ai/domain/controller/AiController.java, ai/src/main/java/com/sparta/ai/domain/dto/response/AiMessageResponseDto.java, ai/src/main/java/com/sparta/ai/domain/service/AiService.java, ai/src/main/java/com/sparta/ai/model/repository/AiMessageRepository.java, ai/src/main/java/com/sparta/ai/model/repository/AiMessageRepositoryCustom.java, ai/src/main/java/com/sparta/ai/model/repository/AiMessageRepositoryCustomImpl.java
- feature/ai-api -> develop
- QueryDsl을 통해 username을 기반으로 검색하는 기능 구현
=> feat: AI 메시지 검색 기능 구현

Hub/src/main/resources/application.properties
=> fix : application.properties 삭제

Hub/src/main/java/com/sparta/Hub/domain/controller/HubRouteController.java, Hub/src/main/java/com/sparta/Hub/domain/dto/response/GetHubRouteInfoRes.java, Hub/src/main/java/com/sparta/Hub/domain/service/HubRouteService.java, Hub/src/main/java/com/sparta/Hub/domain/service/HubService.java, Hub/src/main/java/com/sparta/Hub/model/entity/Hub.java, Hub/src/main/java/com/sparta/Hub/model/repository/HubCustomRepositoryImpl.java, Hub/src/main/resources/data.sql
- feat-6-hubRouteCreate - develop
- x-user-name 삭제
=> Feat 6 hub route create

company/build.gradle, company/src/main/java/com/sparta/company/domain/service/CompanyService.java, company/src/main/java/com/sparta/company/excpetion/CompanyExceptionMessage.java, company/src/main/java/com/sparta/company/infrastructure/dto/GetHubInfoRes.java
- feature/company-api -> main
- Company 서비스에 허브 관련 검증 로직 추가
- zipkin 의존성 추가
=> refactor: Company 서비스에 허브 관련 검증 로직 추가

gateway/build.gradle, gateway/src/main/resources/application.yml
- feature/gateway -> develop
- zipkin 의존성 및 application.yml에 설정 추가
=> chore: zipkin 의존성 추가

user/build.gradle, user/src/main/java/com/sparta/user/domain/controller/UserController.java, user/src/main/java/com/sparta/user/exception/GlobalExceptionHandler.java, user/src/main/java/com/sparta/user/model/repository/UserRepositoryCustomImpl.java, user/src/main/resources/application.yml
- feature/user-api -> main
- Valid 어노테이션에서 발생하는 에러 핸들러 추가
- 검색 API에 sort, page 옵션을 처리할 수 있도록 로직 변경
- zipkin 의존성 추가
=> refactor: User 에러 핸들러, 검색 API 리팩토링 및 zipkin 의존성 추가

ai/build.gradle, ai/src/main/java/com/sparta/ai/domain/controller/AiController.java, ai/src/main/java/com/sparta/ai/model/repository/AiMessageRepositoryCustomImpl.java, ai/src/main/resources/application.yml
- feature/ai-api -> develop
- AI zipkin 의존성 추가 및 application.yml 설정 추가
- AI 검색 API에서 sort, page 옵션을 처리할 수 있도록 로직 변경
=> refactor:  AI 검색 API 리팩토링 및 zipkin 의존성 추가

company/src/main/java/com/sparta/company/domain/controller/CompanyController.java, company/src/main/java/com/sparta/company/model/repository/CompanyRepositoryCustomImpl.java, company/src/main/resources/application.yml
- feature/company-api -> develop
- Company 검색 API에 sort, page 옵션을 처리할 수 있도록 로직 변경
- application.yml zipkin 설정 추가
=> refactor: Company 검색 API 리팩토링 및 zipkin 의존성 추가

product/build.gradle, product/src/main/java/com/sparta/product/domain/controller/ProductController.java, product/src/main/java/com/sparta/product/domain/dto/request/ProductRequestDto.java, product/src/main/java/com/sparta/product/domain/dto/request/UpdateProductRequestDto.java, product/src/main/java/com/sparta/product/domain/dto/response/ProductResponseDto.java, product/src/main/java/com/sparta/product/domain/service/ProductService.java, product/src/main/java/com/sparta/product/exception/GlobalExceptionHandler.java, product/src/main/java/com/sparta/product/model/entity/Product.java, product/src/main/java/com/sparta/product/model/repository/ProductRepositoryCustomImpl.java
- feature/product-api -> develop
- ProductRequestDto productId 필드 제거
- ProductRequestDto, UpdateProductRequestDto에 count 필드 추가 및 Min 어노테이션 추가
- Update 시 productName 또는 Count만 처리할 수 있도록 로직 변경
- 기타 GlobalExceptionHandler 및 QueryDsl 커스텀 Repository 수정
=> refactor: Product에 count 필드 추가 및 관련 로직 수정

user/src/main/java/com/sparta/user/exception/GlobalExceptionHandler.java
- feature/user-api -> develop
- User GlobalExceptionHandler에서 error 필드만 가져와서 응답하도록 변경
=> refactor: User GlobalExceptionHandler에서 error 필드만 가져와서 응답하도록 변경

product/src/main/java/com/sparta/product/domain/service/ProductService.java
- feature/product-api -> develop
- 상품 단건 조회 시 count가 포함되도록 변경
=> refactor: 상품 단건 조회 시 count가 포함되도록 변경

user/build.gradle, user/src/main/java/com/sparta/user/config/SwaggerConfig.java, user/src/main/java/com/sparta/user/domain/controller/UserController.java, user/src/main/java/com/sparta/user/domain/controller/swagger/UserControllerDocs.java, user/src/main/java/com/sparta/user/exception/GlobalExceptionHandler.java, user/src/main/resources/application.yml
- feature/user-api -> develop
- User 서비스 swagger 코드 추가
=> feat: User swagger 코드 추가

user/src/main/java/com/sparta/user/config/SwaggerConfig.java
- feature/user-api -> develop
-  User swagger에서 authorize를 활성화하도록 변경
=> refactor: User swagger에서 authorize를 활성화하도록 변경

ai/build.gradle, ai/src/main/java/com/sparta/ai/config/SwaggerConfig.java, ai/src/main/java/com/sparta/ai/exception/GlobalExceptionHandler.java, ai/src/main/resources/application.yml
- feature/ai -> develop
- ai swagger 설정
=> chore: ai swagger 설정

product/build.gradle, product/src/main/java/com/sparta/product/config/SwaggerConfig.java, product/src/main/java/com/sparta/product/exception/GlobalExceptionHandler.java, product/src/main/resources/application.yml
- [] 기능 추가
- feature/product -> develop
- product swagger 설정
=> chore: product swagger 설정

slack/build.gradle, slack/src/main/java/com/sparta/slack/config/SwaggerConfig.java, slack/src/main/java/com/sparta/slack/exception/GlobalExceptionHandler.java, slack/src/main/resources/application.yml
- [] 기능 추가
- feature/slack -> develop
- slack swagger 설정
=> chore: slack swagger 설정

company/src/main/java/com/sparta/company/config/SwaggerConfig.java
- [] 기능 추가
- feature/company -> develop
- company swagger 설정
=> chore: company swagger 설정

shipment/build.gradle, shipment/src/main/java/com/sparta/shipment/config/SwaggerConfig.java, shipment/src/main/java/com/sparta/shipment/exception/GlobalExceptionHandler.java, shipment/src/main/resources/application.yml
- [] 기능 추가
- [x ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- feature/shipment -> develop
- shipment swagger 설정
=> chore: shipment swagger 설정

shipment/src/main/java/com/sparta/shipment/domain/controller/ShipmentController.java, shipment/src/main/java/com/sparta/shipment/domain/controller/ShipmentManagerController.java, shipment/src/main/java/com/sparta/shipment/domain/controller/ShipmentRouteController.java, shipment/src/main/java/com/sparta/shipment/model/repository/ShipmentManagerRepositoryImpl.java, shipment/src/main/java/com/sparta/shipment/model/repository/ShipmentRepositoryImpl.java, shipment/src/main/java/com/sparta/shipment/model/repository/ShipmentRouteRepositoryImpl.java
- feature/shipment -> develop
- shipment 페이징, orderBy 수정
- shipmentManager 페이징, orderBy 수정
- shipmentRoute 페이징, orderBy 수정
=> chore: shipment 페이징과 orderBy 수정

gateway/build.gradle, gateway/src/main/java/com/sparta/gateway/filter/LocalAuthenticationFilter.java, gateway/src/main/resources/application.yml
- feature/gateway-api -> develop
- Gateway에서 Swagger 통합 관리를 위한 설정 추가
=> feat: Gateway에서 Swagger 통합 관리를 위한 설정 추가

product/src/main/java/com/sparta/product/domain/service/ProductService.java
- feature/product-api -> develop
- Product 서비스에서 fallback 로직을 메서드로 분리 및 폴백 메서드 추가
- 조회, 검색 시 fallback 메서드를 추가
=> refactor: Product 서비스에서 fallback 로직을 메서드로 분리 및 폴백 메서드 추가

shipment/src/main/java/com/sparta/shipment/domain/dto/ShipmentManagerSearchDto.java, shipment/src/main/java/com/sparta/shipment/domain/service/ShipmentManagerService.java, shipment/src/main/java/com/sparta/shipment/domain/service/ShipmentRouteService.java, shipment/src/main/java/com/sparta/shipment/domain/service/ShipmentService.java, shipment/src/main/java/com/sparta/shipment/exception/ServiceNotAvailableException.java
- feature/shipment -> develop
- shipment circuitBreaker fallback 설정
- shipmentRoute circuitBreaker fallback 설정
- shipmentManager circuitBreaker fallback 설정
=> feat: shipment 관련 서비스 CircuitBreaker 설정

gateway/src/main/resources/application.yml
- feature/{도메인}-api -> main
- order, shipment swagger로 접근할 수 있도록 url 추가
=> chore: gateway route 설정 변경
